apiVersion: v1
kind: ConfigMap
metadata:
  name: seafile-env
data:
  # for Seafile server
  TIME_ZONE: "UTC"
  SEAFILE_LOG_TO_STDOUT: "false"
  SITE_ROOT: "/"
  ENABLE_SEADOC: "false"
  SEADOC_SERVER_URL: "https://seafile.example.com/sdoc-server" # only valid in ENABLE_SEADOC = true
  SEAFILE_SERVER_HOSTNAME: "seafile.example.com"
  SEAFILE_SERVER_PROTOCOL: "http"


  # for database
  SEAFILE_MYSQL_DB_HOST: "<your MySQL host>"
  SEAFILE_MYSQL_DB_PORT: "3306"
  SEAFILE_MYSQL_DB_USER: "seafile"
  SEAFILE_MYSQL_DB_CCNET_DB_NAME: "ccnet_db"
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile_db"
  SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: "seahub_db"

  # for cached
  CACHE_PROVIDER: "redis" # or "memcached"

  ## for redis
  REDIS_HOST: "<your redis host>"
  REDIS_PORT: "6379"

  ## for memcached
  MEMCACHED_HOST: "<your memcached host>"
  MEMCACHED_PORT: "11211"

  # for S3
  USE_S3_STORAGE: "false"
  S3_COMMIT_BUCKET: ""
  S3_FS_BUCKET: ""
  S3_BLOCK_BUCKET: ""
  S3_KEY_ID: ""
  S3_USE_V4_SIGNATURE: "true"
  S3_AWS_REGION: "us-east-1"
  S3_HOST: ""
  S3_USE_HTTPS: "true"
  S3_PATH_STYLE_REQUEST: "false"

  # Init
  ## for Seafile admin
  INIT_SEAFILE_ADMIN_EMAIL: "<Seafile admin's email>"
