apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-pro-mc:12.0-latest
          env:
            - name: SEAFILE_SERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_SERVER_HOSTNAME
            - name: SEAFILE_SERVER_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_SERVER_PROTOCOL
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: TIME_ZONE
            - name: SEAFILE_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_LOG_TO_STDOUT
            - name: SITE_ROOT
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SITE_ROOT
            - name: ENABLE_SEADOC
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: ENABLE_SEADOC
            - name: SEADOC_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEADOC_SERVER_URL
            - name: SEAFILE_MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_HOST
            - name: SEAFILE_MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_PORT
            - name: SEAFILE_MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_USER
            - name: SEAFILE_MYSQL_DB_CCNET_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_CCNET_DB_NAME
            - name: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
            - name: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
            - name: SEAF_SERVER_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAF_SERVER_STORAGE_TYPE
            - name: S3_COMMIT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_COMMIT_BUCKET
            - name: S3_FS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_FS_BUCKET
            - name: S3_BLOCK_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_BLOCK_BUCKET
            - name: S3_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_KEY_ID
            - name: S3_USE_V4_SIGNATURE
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_USE_V4_SIGNATURE
            - name: S3_AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_AWS_REGION
            - name: S3_HOST
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_HOST
            - name: S3_USE_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_USE_HTTPS
            - name: S3_PATH_STYLE_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: S3_PATH_STYLE_REQUEST
            - name: INIT_SEAFILE_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: INIT_SEAFILE_ADMIN_EMAIL
            - name: CACHE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: CACHE_PROVIDER
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: REDIS_PORT
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: MEMCACHED_HOST
            - name: MEMCACHED_PORT
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: MEMCACHED_PORT
            - name: NOTIFICATION_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: NOTIFICATION_SERVER_URL
            - name: ENABLE_SEAFILE_AI
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: ENABLE_SEAFILE_AI
            - name: SEAFILE_AI_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: seafile-env
                  key: SEAFILE_AI_SERVER_URL
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: JWT_PRIVATE_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_MYSQL_DB_PASSWORD
            - name: DB_ROOT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
            - name: INIT_SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: INIT_SEAFILE_ADMIN_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: REDIS_PASSWORD
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: S3_SECRET_KEY
            - name: S3_SSE_C_KEY
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: S3_SSE_C_KEY
            - name: SEAFILE_AI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: JWT_PRIVATE_KEY
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred