apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # if you would like to use PV bound from a storage class, please uncomment the following line
  # storageClassName: <your storage class>