name: Deploy CI - 13.0

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-material-extensions mike
      - run: cd $GITHUB_WORKSPACE
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@seafile.com
      - run: mike deploy --push -u 13.0 latest
